module.exports = Object.freeze({
    OP_DUTCHING: "dutching",
    OP_REFUND: "refund",
    OP_UBRIS: "ubris",

    OP_ID : "id",
    OP_NAME: "name",
    OP_AREA: "area",
    OP_OPERATION: "operation",
    OP_OUTCOME_COEFFICIENT: "area_outcome_coefficient",
    OP_GOALNUMBER_COEFFICIENT: "area_goalnumber_coefficient",
    OP_GOALDISTRIBUTION_COEFFICIENT: "area_goaldistribution_coefficient",
    OP_REFUND_PERCENTAGE: "refund_percentage",
    UBRIS_RUNNER_WIN2_CODE: "ubrisRunnerWin2Code",
    UBRIS_RUNNER_WIN1_CODE: "ubrisRunnerWin1Code",
    UBRIS_RUNNER_VOID_CODE: "ubrisRunnerVOIDCode",
    DUTCHING_RUNNER1_CODE: "dutchingRunner1Code",
    DUTCHING_RUNNER2_CODE: "dutchingRunner2Code",
    DUTCHING_RUNNER3_CODE: "dutchingRunner3Code",
    DUTCHING_RUNNER4_CODE: "dutchingRunner4Code",
    REFUND_RUNNER_VOID1_CODE: "refundRunnerVoid1Code",
    REFUND_RUNNER_VOID2_CODE: "refundRunnerVoid2Code",
    REFUND_RUNNER_VOID3_CODE: "refundRunnerVoid3Code",
    REFUND_RUNNER_VOID4_CODE: "refundRunnerVoid4Code",
    REFUND_RUNNER_WIN1_CODE: "refundRunnerWin1Code",
    REFUND_RUNNER_WIN2_CODE: "refundRunnerWin2Code",
    REFUND_RUNNER_WIN3_CODE: "refundRunnerWin3Code",
    REFUND_RUNNER_WIN4_CODE: "refundRunnerWin4Code",
});